### ISSUE TITLE
About "pmp-library".

### ISSUE THREAD

**Issue by KelSolaar** [nschloe/awesome-scientific-computing#28]
Hey @nschloe,

I was wondering if this one would be a good fit in the [Meshing](https://github.com/nschloe/awesome-scientific-computing#meshing) category: http://www.pmp-library.org/

It is not purely _meshing_ but more _remeshing_ actually.

I can create a PR nonetheless!

Cheers,

Thomas

**Comment by nschloe** [comment]
Sure, why not? Best simply create a PR, I can always merge or close it then.

**Comment by KelSolaar** [comment]
Cool will do!
