### ISSUE TITLE
Add a section on mesh visualization?

### ISSUE THREAD

**Issue by liubenyuan** [nschloe/awesome-scientific-computing#38]
Hi, I do not know whether there exist some good quality mesh visualization tools, triangles in 2D and tetrahedral in 3D. Could we add a section on this topic?

**Comment by nschloe** [comment]
Good idea.

**Comment by liubenyuan** [comment]
I know the following two: [paraview](https://www.paraview.org/) and [polyscope](https://polyscope.run/)

I want to visualize the FEM results in 2D and 3D using both python and C++ (embedded in my GUI applications).
