### ISSUE TITLE
add VisIt in visualisation

### ISSUE THREAD

**Issue by blacheref** [nschloe/awesome-scientific-computing#60]
Hi, would it be possible to add VisIt https://wci.llnl.gov/simulation/computer-codes/visit and https://github.com/visit-dav/visit/ in the section visualization ?

**Comment by nschloe** [comment]
I got VisIt on my radar, but I got to say I don't find it too awesome. Installation alone is a pain. I might change my mind if it found its way into a bunch of Linux distros.

**Comment by blacheref** [comment]
Yeah, compiling from source it's quite complex but the binaries provided works well on various distro (ubuntu, arch, centos, ...). One "significant" feature is the `Reopen` button which was missing in paraview in old releases.

**Comment by nschloe** [comment]
I never really got it to work. Also, the website and the UI look like they haven't been updated in while. I wouldn't recommend it over ParaView.

![screenshot](https://user-images.githubusercontent.com/181628/106874880-5f218980-66d6-11eb-896f-e97a547964a5.png)
